# Generated by Django 4.1.3 on 2022-11-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_transaction_journalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
